[package]
name = "holidays-related-to-easter"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Holidays_related_to_Easter"

[dependencies]
chrono = "0.4"