[package]
name = "p-value-correction"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/P-value_correction"


[dev-dependencies]
assert_approx_eq = "1.1.0"