[package]
name = "cheryl-birthday"
version = "0.1.0"
authors = ["Lucas De Angelis <deangelis.lucas@outlook.com>"]
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Cheryl%27s_birthday"