[package]
name = "bernoulli-numbers"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Bernoulli_numbers"

[dependencies]
num = "0.4.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "benchmarks"
harness = false
