[package]
name = "fivenum"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Fivenum"

[dependencies]

[dev-dependencies]
assert_approx_eq = "1.1.0"
