[package]
name = "harmonic-series"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Harmonic_series"

[dependencies]
num = "0.4.0"