[package]
name = "linear-congruential-generator"
version = "0.1.0"
edition = "2021"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Linear_congruential_generator"

[dependencies]
rand = "0.8.5"
rand_core = "0.6.3"
